sudo: required
services: 
  - docker

before_install:
  - docker build -t jkolden/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jkolden/react-test npm test -- --coverage

after_success:
  - docker build -t jkolden/multi-client ./client
  - docker build -t jkolden/multi-nginx ./nginx
  - docker build -t jkolden/multi-server ./hr_node_app

  # push images to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push jkolden/multi-nginx
  - docker push jkolden/multi-server
  - docker push jkolden/multi-client