version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./hr_node_app
    volumes:
      - /app/node_modules
      - ./hr_node_app:/app
    environment:
      - TNS_ADMIN=/app/Wallet_DB201909100942
      - NODE_ORACLEDB_PASSWORD=Jaka!00000928
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
