version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./hr_node_app
    volumes:
      - /app/node_modules
      - ./hr_node_app:/app
    environment:
      - TNS_ADMIN=/usr/src/app/Wallet_DB201909100942
      - NODE_ORACLEDB_PASSWORD=Jaka!00000928
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client 
    volumes:
      - /app/node_modules
      - ./client:/app